# Fragment folder
frag_dir: "/oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/data/frags"
barcode_dir: "/oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/results/2_chrombpnet/barcode"
out_dir: "/oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/results/2_chrombpnet/inputs"
genome_dir: "/oak/stanford/groups/akundaje/leixiong/genome"

frag_suffix: ".tsv"
barcode_suffix: ".txt"
peak_suffix: "_peaks_overlap_filtered.narrowPeak"


output:
  sample_fragments: "1_sample_fragments"
  celltype_fragments: "2_celltype_fragments"
  peaks: "3_peaks"
  bigwig: "4_bigwig"
  union_peaks: "5_union_peak/union_peaks.narrowPeak"


genome_build: hg38
genome:
  hg38:
    fasta: "hg38.fa"
    chrom_sizes: "hg38.chrom.sizes"
    blacklist: "blacklist.bed.gz"
    bias_model: "bias.h5"
    chr_fold: "splits"
  mm10:
    fasta: "mm10.fa"
    chrom_sizes: "mm10.chrom.sizes"
    blacklist: "mm10.blacklist2.bed"
    bias_model: "bias.h5"
    chr_fold: "splits"

cell_types: 
