# Fragment folder
input_frag_dir: "/users/leixiong/projects/imac_igvf/data/frags"
input_barcode_dir: "/users/leixiong/projects/imac_igvf/2_chrombpnet/0_barcode/cell_type0"
out_dir: "/users/leixiong/oak/tmp/preprocessing"
genome_dir: "/oak/stanford/groups/akundaje/leixiong/genome"

frag_suffix: ".tsv.gz"
barcode_suffix: ".txt"
peak_suffix: "_peaks_overlap_filtered.narrowPeak"

sample_fragments: "1_sample_fragments"
celltype_fragments: "2_celltype_fragments"
output:
  sample_fragments: 
    fragments: "fragments"
    pseudorep1: "pseudorep1"
    pseudorep2: "pseudorep2"
    pseudorepT: "pseudorepT"
  celltype_fragments: 
    fragments: "fragments"
    pseudorep1: "pseudorep1"
    pseudorep2: "pseudorep2"
    pseudorepT: "pseudorepT"
  peaks: "3_peaks"
  bigwig: "4_bigwig"
  union_peak: "5_union_peak"


genome_build: hg38
genome:
  hg38:
    fasta: "hg38.fa"
    chrom_sizes: "hg38.chrom.sizes"
    blacklist: "blacklist.bed.gz"
    bias_model: "bias.h5"
    chr_fold: "splits"
  mm10:
    fasta: "mm10.fa"
    chrom_sizes: "mm10.chrom.sizes"
    blacklist: "mm10.blacklist2.bed"
    bias_model: "bias.h5"
    chr_fold: "splits"

celltypes:
