import os
import numpy as np

configfile: "config.yaml"

output_config = {i: os.path.join(config['out_dir'], config["output"][i]) for i in config["output"]}
sample_frag_dir = output_config["sample_fragments"]
celltype_frag_dir = output_config["celltype_fragments"]
peak_dir = output_config["peaks"]
bigwig_dir= output_config["bigwig"]
union_peaks = output_config["union_peaks"]
genome_build = config["genome_build"]
genome_config = {i: os.path.join(config['genome_dir'], genome_build, config["genome"][genome_build][i]) for i in config["genome"][genome_build]}

CELLTYPES = np.unique([
        fname.replace(config["barcode_suffix"], "").split('-')[1]
        for fname in os.listdir(config["barcode_dir"])
        if fname.endswith(config["barcode_suffix"])
    ])

SAMPLES  = np.unique([
        fname.replace(config["barcode_suffix"], "").split('-')[0]
        for fname in os.listdir(config["barcode_dir"])
        if fname.endswith(config["barcode_suffix"])
    ])

SUBFOLDS = ["fragments", "pseudorep1", "pseudorep2", "pseudorepT"]


def list_input_fragment_files(wildcards):
    return expand(config["frag_dir"]+"/{sample}" + config['frag_suffix'], sample=SAMPLES)

def list_input_barcode_files(wildcards):
    return expand(config["barcode_dir"] + "/{sample}-{cell_type}.txt", sample=SAMPLES, cell_type=CELLTYPES)

def list_sample_fragment_files(wildcards):
    output = expand(sample_frag_dir+"/{subfolder}/{cell_type}-{sample}.tsv", subfolder=SUBFOLDS, sample=SAMPLES, cell_type=CELLTYPES)
    return output

def list_celltype_fragment_files(wildcards):
    output = expand(celltype_frag_dir + "/{subfolder}/{cell_type}_sorted.tsv", subfolder=SUBFOLDS, cell_type=CELLTYPES)
    return output

def list_peak_files(wildcards):
    output = expand(peak_dir+"/{cell_type}"+config["peak_suffix"], cell_type=CELLTYPES)
    return output

def list_bigwig_files(wildcards):
    output = expand(bigwig_dir + "/{cell_type}_unstranded.bw", cell_type=CELLTYPES)
    return output

shell.prefix("source scripts/env_setup.sh")

include: "rules/zcat.smk"
include: "rules/extract_sample_fragments.smk"
include: "rules/group_celltype.smk"
include: "rules/callpeak.smk"
include: "rules/make_bigwig.smk"
include: "rules/union_peaks.smk"

rule all:
    input:
        # list_input_fragment_files,
        list_sample_fragment_files,
        list_celltype_fragment_files,
        list_peak_files,
        list_bigwig_files, 
        union_peaks



