####################################################################################
# User customized configuration file for chrombpnet
####################################################################################

# Configuration for paths and parameters

# Peak dir: peak_dir/{cell_type}{peak_suffix}, union_peak is a merged peak file over all peak files
peak_dir: #"inputs/3_peaks" e.g. /oak/stanford/groups/akundaje/leixiong/projects/macro_atlas/pancancer/output/inputs/3_peaks
peak_suffix: #"_peaks_overlap_filtered.narrowPeak"  # Peak file suffix
union_peak: # "union_peaks.narrowPeak" e.g. /oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/results/2_chrombpnet/inputs/5_union_peak/union_peaks.narrowPeak

# Input files either fragments or bam files:
# input_dir: input_dir/{cell_type}{input_suffix}
input_dir: # inputs/2_celltype_fragments/fragments e.g. /oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/results/2_chrombpnet/inputs/2_celltype_fragments/fragments
input_suffix:   # _sorted.tsv / .bam
format:  # frag / bam

out_dir: # "/oak/stanford/groups/akundaje/leixiong/projects/imac_igvf/results/2_chrombpnet/output"

# Genome and motif directories
genome_dir: "/oak/stanford/groups/akundaje/leixiong/genome"
motif_dir: "/oak/stanford/groups/akundaje/leixiong/genome/motifs"

####################################################################################

# Genome configuration include bias for running chrombpnet
genome_build: hg38
genome:
  hg38:
    fasta: "hg38.fa"
    chrom_sizes: "hg38.chrom.sizes"
    blacklist: "blacklist.bed.gz"
    bias_model: "bias.h5"
    chr_fold: "splits"
  mm10:
    fasta: "mm10.fa"
    chrom_sizes: "mm10.chrom.sizes"
    blacklist: "mm10-blacklist.v2.bed.gz"
    bias_model: "bias.h5"
    chr_fold: "splits"

fold: ['fold_0', 'fold_1', 'fold_2', 'fold_3', 'fold_4']

# Modisco configuration files
motif:
  motif_to_pwm: "motif_to_pwm.tsv"
  meme_db: "all.dbs.meme" #"motifs.meme.txt"


modisco:
  max_seqlets: 1000000
  num_leiden: 2
  num_matches: 10


# Chrombpnet output directories
out:
  model_dir: "models"
  negative_dir: "negatives"
  modisco_dir: "modisco"
  shap_dir: "shap"
  hitcaller_dir: "hitcaller"

use_union_peaks: false
head: ['counts'] #, 'profile']

alpha: 0.8 # alpha for hitcaller

tmpdir: "/tmp"
