# from snakemake.utils import min_version
# min_version("5.4")

configfile: "config.yaml"


# include: "rules/negatives.smk"

import os
genome_build = config["genome_build"]
genome_config = {i: os.path.join(config['genome_dir'], genome_build, config["genome"][genome_build][i]) for i in config["genome"][genome_build]}
output_config = {i: os.path.join(config['out_dir'], config["out"][i]) for i in config["out"]}
motif_config = {i: os.path.join(config['motif_dir'], config["motif"][i]) for i in config["motif"]}


CELLTYPES = [
        fname.replace(config["peak_suffix"], "")
        for fname in os.listdir(config["peak_dir"])
        if fname.endswith(config["peak_suffix"])
    ]

FOLDS=config['fold']


# Union negatives
# def list_negatives(wildcards):   
#     return expand(output_config['negative_dir']+"/{fold}_negatives.bed", fold=FOLDS)

def list_models(wildcards):
    return expand(output_config["model_dir"]+"/{cell_type}/{fold}/models/chrombpnet_nobias.h5", cell_type=CELLTYPES, fold=config['fold'])

def list_shap(wildcards):
    return expand(output_config["shap_dir"] + "/{cell_type}/{fold}.{head}_scores.bw", cell_type=CELLTYPES, fold=config['fold'], head=config['head'])

def list_modisco(wildcards):
    return expand(output_config["modisco_dir"] + "/{cell_type}/{head}_modisco.h5", cell_type=CELLTYPES, head=config['head'])

def list_hitcaller(wildcards):
    return expand(output_config["hitcaller_dir"] + "/{cell_type}/{head}/hits.bed.gz", cell_type=CELLTYPES, head=config['head'])



shell.prefix("source scripts/env_setup.sh")

rule all:
    input: 
        list_models,
        list_shap,
        list_modisco,
        list_hitcaller

rule test_gpu:
    # output:
    #     # "test_gpu.txt"
    # resources:
    #     gpu=1
    conda:
        "chrombpnet"
    shell:
        """
        python - <<EOF
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
EOF
        """



rule negatives:
    input:
        peaks = config["union_peak"]
    output:
        output_config["negative_dir"] + "/{fold}_negatives.bed"
    params:
        peak_dir = config["peak_dir"],
        fasta = genome_config['fasta'],
        chrom_sizes = genome_config['chrom_sizes'], 
        chr_fold = genome_config['chr_fold'], 
        blacklist = genome_config['blacklist'],
        output_prefix = output_config["negative_dir"] + "/{fold}"
    conda:
        "chrombpnet"
    shell:
        """
        if [[ -f {output} ]];
        then
            echo "Found negatives"
        else
            echo "Preparing {output}"
            if [[ -d {params.output_prefix}_auxiliary ]];
            then
                echo "Found logdir. Deleting previous fold"
                rm -rf {params.output_prefix}_auxiliary
            fi
            chrombpnet prep nonpeaks \
                -p {input} \
                -o {params.output_prefix} \
                -g {params.fasta} \
                -c {params.chrom_sizes} \
                -fl {params.chr_fold}/{wildcards.fold}.json \
                -br {params.blacklist}
        fi
        """


rule train:
    input:
        input_file = config["input_dir"] + "/{cell_type}" + config['input_suffix'], 
        peaks = config['union_peak'], 
        negatives = output_config["negative_dir"] + "/{fold}_negatives.bed", 
        bias_model = genome_config["bias_model"],
    output:
        "{model_dir}/{cell_type}/{fold}/models/chrombpnet_nobias.h5"
    params:
        model_dir = output_config["model_dir"],
        out_dir = output_config['model_dir'] + "/{cell_type}/{fold}",
        fasta = genome_config["fasta"],
        chrom_sizes = genome_config["chrom_sizes"],
        chr_fold = genome_config["chr_fold"],
        format = config['format']
    resources:
        nvidia_gpu=1,
        mem_gb=30
    threads: 1
    conda:
        "chrombpnet"
    shell:
        """
        if [[ -f {output} ]]; then
            echo "Found model"
        else
            if [[ -d {params.out_dir} ]]; then
                echo "Found logdir. Deleting previous model"
                rm -rf {params.out_dir}
            fi

            echo "Training model"
            chrombpnet pipeline \
                -i{params.format} {input.input_file} \
                -p {input.peaks} \
                -n {input.negatives} \
                -b {input.bias_model} \
                -o {params.out_dir} \
                -g {params.fasta} \
                -c {params.chrom_sizes} \
                -fl {params.chr_fold}/{wildcards.fold}.json \
                -d "ATAC" 
        fi
        """

rule deepshap:
    input:
        model = output_config["model_dir"] + "/{cell_type}/{fold}/models/chrombpnet_nobias.h5",
        union_peak = config["union_peak"],
    output: 
        profile_shap = output_config["shap_dir"] + "/{cell_type}/{fold}.profile_scores.bw",
        counts_shap = output_config["shap_dir"] + "/{cell_type}/{fold}.counts_scores.bw",
        profile_shap_h5 = output_config["shap_dir"] + "/{cell_type}/{fold}.profile_scores.h5",
        counts_shap_h5 = output_config["shap_dir"] + "/{cell_type}/{fold}.counts_scores.h5"
    params:
        fasta = genome_config["fasta"],
        chrom_sizes = genome_config["chrom_sizes"],
        output_prefix = output_config["shap_dir"] + "/{cell_type}/{fold}",
        shap_dir = output_config["shap_dir"]
    resources:
        nvidia_gpu=1,
        mem_gb=100
    conda:
        "chrombpnet"
    shell:
        """
        mkdir -p {params.shap_dir}
        if [[ -f {output.profile_shap} ]]; then
            echo "Found shap scores"
        else
            echo "Generate contribution score bigwigs"
            chrombpnet contribs_bw \
                -m {input.model} \
                -r {input.union_peak} \
                -g {params.fasta} \
                -c {params.chrom_sizes} \
                -op {params.output_prefix} \
                -d "chr1"
        fi
        """

rule average_shap:
    input:
        lambda wildcards: expand(output_config["shap_dir"] + "/{cell_type}/{fold}.{head}_scores.h5", fold = config['fold'], cell_type=CELLTYPES, head=config['head'])
    output:
        output_config["shap_dir"] + "/{cell_type}/average.{head}.h5",
    params:
        folds = config['fold'],
        base_dir = output_config['shap_dir'] + "/{cell_type}"
    conda:
        "chrombpnet"
    shell:
        """
        python scripts/average_shap.py \
            --shaptype {wildcards.head} \
            --base_dir {params.base_dir} \
            --folds {params.folds}
        """


rule modisco:
    input:
        output_config["shap_dir"] + "/{cell_type}/average.{head}.h5",
    output:
        modisco_output = output_config["modisco_dir"] + "/{cell_type}/{head}_modisco.h5",
        report_html = output_config["modisco_dir"] + "/{cell_type}/modisco/{head}/motifs.html",
        output_memedb = output_config["modisco_dir"] + "/{cell_type}/{head}_motifs.meme",
    params:
        max_seqlets=config['modisco']['max_seqlets'],
        num_leiden=config['modisco']['num_leiden'],
        num_matches=config['modisco']['num_matches'],
        meme_db=motif_config['meme_db'],
        report_outdir=output_config["modisco_dir"] + "/{cell_type}/motiisco/{head}",
        img_suffix_dir="./",
    threads: 4
    conda:
        "chrombpnet"
    shell:
        """
        modisco motifs -i {input} -n {params.max_seqlets} -l {params.num_leiden} -o {output.modisco_output}
        modisco report -i {output.modisco_output} -o {params.report_outdir} -s {params.img_suffix_dir} -m {params.meme_db} -n {params.num_matches}
        modisco meme -i {output.modisco_output} -t PFM -o {output.output_memedb}
        """

rule make_contrib_bw:
    input:
        output_config["shap_dir"] + "/{cell_type}/average.{head}.h5",
    output:
        output_config["shap_dir"] + "/{cell_type}/average.{head}.bw",
    params:
        chrom_sizes = genome_config["chrom_sizes"],
        output_prefix = output_config["shap_dir"] + "/{cell_type}/average.{head}",
        peaks_file = config["union_peak"]    
    shell:
        """
        python3.8 scripts/importance_hdf5_to_bigwig.py \
            --hdf5 {input} \
            --regions {params.peaks_file} \
            --chrom-sizes {params.chrom_sizes} \
            --output-prefix {params.output_prefix}
        """

rule generate_prediction:
    input:
        models = expand(output_config["model_dir"] + "/{cell_type}/{fold}/models/chrombpnet_nobias.h5", cell_type=CELLTYPES, fold=config['fold']),
        peaks_file = config["union_peak"],
    output:
    params:
    conda:
        "chrombpnet"
    shell:
        """
        python scripts/predict_and_avg.py \
            {input.peaks_file} \
            {params.fasta} \
            {params.chrom_sizes} \
            {params.output_prefix} \
            {input.models}
        """


rule hitcaller:
    input:
        shap_h5 = output_config["shap_dir"] + "/{cell_type}/average.{head}.h5",
        modisco_h5 = output_config["modisco_dir"] + "/{cell_type}/{head}_modisco.h5",
        peaks_bed = config["union_peak"],
    output:
        finemo_npz = output_config["hitcaller_dir"] + "/{cell_type}/{head}/regions.npz",
        finemo_hits = output_config["hitcaller_dir"] + "/{cell_type}/{head}/hits.tsv",
        finemo_bed = output_config["hitcaller_dir"] + "/{cell_type}/{head}/hits.bed.gz",
    params:
        finemo_out = output_config["hitcaller_dir"] + "/{cell_type}/{head}",
        alpha = 0.6,
    conda:
        "finemo_gpu"
    shell:
        """
        finemo extract-regions-h5 --h5s {input.shap_h5} --out-path {output.finemo_npz} --region-width 1000
        finemo call-hits --regions {output.finemo_npz} --modisco-h5 {input.modisco_h5} --peaks {input.peaks_bed} --alpha {params.alpha} --out-dir {params.finemo_out}
        finemo report --hits {output.finemo_hits} --regions {output.finemo_npz} --modisco-h5 {input.modisco_h5} --peaks {input.peaks_bed} --out-dir {params.finemo_out}

        if [[ -f "{params.finemo_out}/hits.bed" ]]; then 
            
            # bgzip and index hits
            module load biology samtools

            bgzip -c {params.finemo_out}/hits.bed > {params.finemo_out}/hits.bed.gz
            tabix -p bed {params.finemo_out}/hits.bed.gz

        fi
        """

rule footprints:
    input:
    output:
    params:
    shell:
        """
        footprints \
            -i H5PY \
            -o OUTPUT_PREFIX \
            #[-l N_LEIDEN] [-w WINDOW] [-v]

        """

rule make_datahub:
    input:
    output:
    params:
    shell:
        """
        make_igv_session \
            -i H5PY \
            -o OUTPUT_PREFIX \
            #[-l N_LEIDEN] [-w WINDOW] [-v]

        """